using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

// -- Entry --
var root   = Helpers.FindRepoRoot();
var outArg = args.FirstOrDefault(a => a.StartsWith("--output=", StringComparison.Ordinal))?.Split('=')[1]
          ?? args.SkipWhile(a => a != "--output").Skip(1).FirstOrDefault()
          ?? Path.Combine(root, ".codemap", "map.md");

var src = Path.Combine(root, "src");
var files = Directory.GetFiles(src, "*.cs", SearchOption.AllDirectories)
    .Where(f => !f.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}")
             && !f.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}")
             && !f.Contains($"{Path.DirectorySeparatorChar}Migrations{Path.DirectorySeparatorChar}"))
    .OrderBy(f => f)
    .ToList();

var parseOpts = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest);
var units     = files.Select(f => ParseFile(f, root, parseOpts)).Where(u => u.Types.Count > 0).ToList();
var commit    = Helpers.RunGit("rev-parse --short HEAD") ?? "unknown";
var totalLines = files.Sum(f => File.ReadLines(f).Count());

// -- Render --
var md = new StringBuilder();
md.AppendLine($"# Code Map — {Path.GetFileName(root)}");
md.AppendLine();
md.AppendLine($"**{files.Count} files** | **{totalLines:N0} lines** | **{units.Sum(u => u.Types.Count)} types** | commit `{commit}`");
md.AppendLine();
md.AppendLine("> Auto-generated by `scripts/codemap`. Do not edit manually.");
md.AppendLine("> Run: `dotnet run --project scripts/codemap`");

// Layers adapted for AgenticWorkforce project structure
var layers = new[]
{
    ("Features",        (Func<UnitInfo, bool>)(u => u.RelPath.Contains("Features"))),
    ("Core",            u => u.RelPath.Contains($"{Path.DirectorySeparatorChar}Core{Path.DirectorySeparatorChar}")),
    ("Domain Entities", u => u.RelPath.Contains("Domain") && u.RelPath.Contains("Entities")),
    ("Domain Interfaces", u => u.RelPath.Contains("Domain") && u.RelPath.Contains("Interfaces")),
    ("Domain Exceptions", u => u.RelPath.Contains("Domain") && u.RelPath.Contains("Exceptions")),
    ("Infrastructure",  u => u.RelPath.Contains("Infrastructure")),
    ("Agents",          u => u.RelPath.Contains("AgenticWorkforce.Agents")),
    ("Worker",          u => u.RelPath.Contains("AgenticWorkforce.Worker")),
    ("AppHost",         u => u.RelPath.Contains("AppHost")),
    ("ServiceDefaults", u => u.RelPath.Contains("ServiceDefaults")),
};

var assigned = new HashSet<UnitInfo>();

foreach (var (layer, pred) in layers)
{
    var layerUnits = units.Where(u => pred(u) && !assigned.Contains(u)).ToList();
    if (layerUnits.Count == 0) continue;
    foreach (var u in layerUnits) assigned.Add(u);

    md.AppendLine();
    md.AppendLine($"## {layer}");

    foreach (var unit in layerUnits.OrderBy(u => u.RelPath))
    {
        md.AppendLine();
        md.AppendLine($"### `{unit.RelPath}`");

        foreach (var type in unit.Types)
        {
            md.AppendLine();
            var kind     = type.Kind switch { "interface" => "Interface", "record" => "Record", "enum" => "Enum", _ => "Class" };
            var baseList = type.Bases.Count > 0 ? $" : {string.Join(", ", type.Bases)}" : "";
            md.AppendLine($"**{kind}** `{type.Name}`{baseList}");

            if (type.Routes.Count > 0)
                md.AppendLine($"> Route: `{string.Join(", ", type.Routes)}`");
            if (type.Injects.Count > 0)
                md.AppendLine($"> Injects: `{string.Join("`, `", type.Injects)}`");

            if (type.Members.Count > 0)
            {
                md.AppendLine();
                md.AppendLine("| Member | Kind | HTTP |");
                md.AppendLine("|---|---|---|");
                foreach (var m in type.Members)
                {
                    var http = m.HttpVerbs.Count > 0 ? string.Join(" ", m.HttpVerbs) : "-";
                    md.AppendLine($"| `{m.Signature}` | {m.Kind} | {http} |");
                }
            }
        }
    }
}

// Remaining unassigned
var rest = units.Where(u => !assigned.Contains(u)).ToList();
if (rest.Count > 0)
{
    md.AppendLine();
    md.AppendLine("## Other");
    foreach (var unit in rest.OrderBy(u => u.RelPath))
    {
        md.AppendLine();
        md.AppendLine($"### `{unit.RelPath}`");
        foreach (var type in unit.Types)
        {
            var kind = type.Kind switch { "interface" => "Interface", "record" => "Record", "enum" => "Enum", _ => "Class" };
            md.AppendLine($"**{kind}** `{type.Name}`");
        }
    }
}

md.AppendLine();
md.AppendLine("## Layer dependencies");
md.AppendLine();
md.AppendLine("```");
md.AppendLine("AppHost     -> Api, Worker                (Aspire orchestration)");
md.AppendLine("Api         -> Domain, Infrastructure     (BFF — auth, middleware, endpoints)");
md.AppendLine("Worker      -> Domain, Infrastructure, Agents (Durable Task, agent execution)");
md.AppendLine("Agents      -> Domain                     (MAF agent wrappers, tools)");
md.AppendLine("Infrastructure -> Domain                  (EF Core, Redis, Azure SDK)");
md.AppendLine("Domain      -> (no dependencies)          (entities, interfaces, exceptions)");
md.AppendLine("```");

Directory.CreateDirectory(Path.GetDirectoryName(outArg)!);
File.WriteAllText(outArg, md.ToString());
Console.WriteLine($"Codemap written -> {outArg}");
Console.WriteLine($"  {units.Sum(u => u.Types.Count)} types across {files.Count} files");

// -- Parse --
static UnitInfo ParseFile(string path, string root, CSharpParseOptions opts)
{
    var src  = File.ReadAllText(path);
    var tree = CSharpSyntaxTree.ParseText(src, opts);
    var unit = new UnitInfo { Path = path, RelPath = path.Replace(root + Path.DirectorySeparatorChar, "") };
    new TypeWalker(unit).Visit(tree.GetRoot());
    return unit;
}

// -- Models --
sealed class UnitInfo
{
    public string Path    { get; set; } = "";
    public string RelPath { get; set; } = "";
    public List<TypeInfo> Types { get; } = [];
}

sealed class TypeInfo(string name, string kind)
{
    public string       Name    { get; } = name;
    public string       Kind    { get; } = kind;
    public List<string> Bases   { get; } = [];
    public List<string> Routes  { get; } = [];
    public List<string> Injects { get; } = [];
    public List<MemberInfo> Members { get; } = [];
}

sealed class MemberInfo(string signature, string kind)
{
    public string       Signature { get; } = signature;
    public string       Kind      { get; } = kind;
    public List<string> HttpVerbs { get; } = [];
}

// -- Walker --
sealed class TypeWalker(UnitInfo unit) : CSharpSyntaxWalker
{
    private static readonly string[] HttpVerbs = ["HttpGet","HttpPost","HttpPut","HttpPatch","HttpDelete","HttpHead"];

    public override void VisitClassDeclaration(ClassDeclarationSyntax node)
        => Visit(node, "class", node.Modifiers, node.Identifier, node.BaseList, node.Members, node.ParameterList);

    public override void VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
        => Visit(node, "interface", node.Modifiers, node.Identifier, node.BaseList, node.Members, null);

    public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
        => Visit(node, "record", node.Modifiers, node.Identifier, node.BaseList, node.Members, null);

    public override void VisitEnumDeclaration(EnumDeclarationSyntax node)
    {
        if (!IsPublic(node.Modifiers)) return;
        unit.Types.Add(new TypeInfo(node.Identifier.Text, "enum"));
    }

    private void Visit(
        SyntaxNode _,
        string kind,
        SyntaxTokenList mods,
        SyntaxToken identifier,
        BaseListSyntax? baseList,
        SyntaxList<MemberDeclarationSyntax> members,
        ParameterListSyntax? primaryCtor)
    {
        if (!IsPublic(mods) && kind != "interface") return;

        var type = new TypeInfo(identifier.Text, kind);

        if (baseList != null)
            foreach (var b in baseList.Types)
                type.Bases.Add(b.Type.ToString());

        foreach (var attrList in GetAttributeLists(_))
            foreach (var attr in attrList.Attributes)
                if (attr.Name.ToString() == "Route" && attr.ArgumentList?.Arguments.Count > 0)
                    type.Routes.Add(attr.ArgumentList.Arguments[0].ToString().Trim('"'));

        if (primaryCtor != null)
            foreach (var p in primaryCtor.Parameters)
            {
                var t = p.Type?.ToString() ?? "";
                if (IsServiceDep(t)) type.Injects.Add(t);
            }

        foreach (var ctor in members.OfType<ConstructorDeclarationSyntax>().Where(c => IsPublic(c.Modifiers)))
            foreach (var p in ctor.ParameterList.Parameters)
            {
                var t = p.Type?.ToString() ?? "";
                if (IsServiceDep(t) && !type.Injects.Contains(t)) type.Injects.Add(t);
            }

        foreach (var m in members)
        {
            var info = MakeMember(m);
            if (info != null) type.Members.Add(info);
        }

        unit.Types.Add(type);
    }

    private static MemberInfo? MakeMember(MemberDeclarationSyntax m)
    {
        if (!IsPublic(Mods(m))) return null;
        switch (m)
        {
            case MethodDeclarationSyntax md:
            {
                var ps  = string.Join(", ", md.ParameterList.Parameters.Select(p => $"{p.Type} {p.Identifier}".Trim()));
                var sig = $"{md.ReturnType} {md.Identifier.Text}({ps})";
                var mi  = new MemberInfo(sig, "Method");
                foreach (var al in md.AttributeLists)
                    foreach (var a in al.Attributes)
                        foreach (var v in HttpVerbs)
                            if (a.Name.ToString() == v) mi.HttpVerbs.Add($"[{v.Replace("Http", "")}]");
                return mi;
            }
            case PropertyDeclarationSyntax pd:
                return new MemberInfo($"{pd.Type} {pd.Identifier.Text}", "Property");
            case ConstructorDeclarationSyntax cd:
            {
                var ps  = string.Join(", ", cd.ParameterList.Parameters.Select(p => p.Type?.ToString() ?? ""));
                return new MemberInfo($"{cd.Identifier.Text}({ps})", "Constructor");
            }
            default: return null;
        }
    }

    private static SyntaxTokenList Mods(MemberDeclarationSyntax m) => m switch
    {
        ClassDeclarationSyntax c       => c.Modifiers,
        InterfaceDeclarationSyntax i   => i.Modifiers,
        RecordDeclarationSyntax r      => r.Modifiers,
        MethodDeclarationSyntax md     => md.Modifiers,
        PropertyDeclarationSyntax p    => p.Modifiers,
        ConstructorDeclarationSyntax c => c.Modifiers,
        _                              => default,
    };

    private static IEnumerable<AttributeListSyntax> GetAttributeLists(SyntaxNode n) => n switch
    {
        ClassDeclarationSyntax c       => c.AttributeLists,
        InterfaceDeclarationSyntax i   => i.AttributeLists,
        RecordDeclarationSyntax r      => r.AttributeLists,
        MethodDeclarationSyntax md     => md.AttributeLists,
        PropertyDeclarationSyntax p    => p.AttributeLists,
        ConstructorDeclarationSyntax c => c.AttributeLists,
        _                              => [],
    };

    private static bool IsPublic(SyntaxTokenList m) => m.Any(t => t.IsKind(SyntaxKind.PublicKeyword));

    private static bool IsServiceDep(string t) =>
        t.Length > 1 && !t.Contains('<') &&
        (t[0] == 'I' || t.EndsWith("Service", StringComparison.Ordinal) ||
         t.EndsWith("Repository", StringComparison.Ordinal) || t.EndsWith("Accessor", StringComparison.Ordinal) ||
         t.EndsWith("Client", StringComparison.Ordinal) || t.Contains("Logger", StringComparison.Ordinal));
}

// -- Helpers --
static class Helpers
{
    public static string FindRepoRoot()
    {
        var d = new DirectoryInfo(AppContext.BaseDirectory);
        while (d != null)
        {
            if (Directory.Exists(Path.Combine(d.FullName, ".git"))) return d.FullName;
            d = d.Parent;
        }
        return Directory.GetCurrentDirectory();
    }

    public static string? RunGit(string args)
    {
        try
        {
            var p = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("git", args)
            { RedirectStandardOutput = true, UseShellExecute = false });
            var o = p?.StandardOutput.ReadToEnd().Trim();
            p?.WaitForExit();
            return o;
        }
        catch { return null; }
    }
}
